---
- name: testing to add ssh key and add user account
  hosts: test-ansible
  remote_user: ubuntu
  become: yes
  vars: 
    ssh_pubkey: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"
   
  tasks:
    - name: test connection
      ping:
      remote_user: ubuntu
    
    - name: create user account
      user:
        name: test-ansible
        shell: /bin/bash
        groups: admin
        append: yes
    
    - name: add ssh key to .ssh
      lineinfile:
        path: '/home/ubuntu/.ssh/authorized_keys'
        line: "{{ssh_pubkey}}"
        mode: 0600
    
    - name: install nginx
      apt: 
        name: nginx
        state: latest
        update_cache: yes
        install_recommends: yes

    - name: install python
      apt: 
        name: python3
        state: latest
        force_apt_get: yes
        update_cache: yes
        install_recommends: yes
    
    - name: install postgresql
      apt: 
        pkg:
        - postgresql
        - postgresql-contrib
        