---
#- name: testing to add ssh key and add user account
#  become: yes
#  vars: 
#    ssh_pubkey: "{{lookup('file', '/var/jenkins_home/aws-key/deploy.pub')}}"
#    new_user: test-ansible

- name: get vars
  include_vars: '../defaults/main.yml'
   
- name: test connection
  ping:
  remote_user: ubuntu

- name: update apt-cache
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install python2
  become: yes
  apt:
    name: python
    state: latest

- name: create user account
  user:
    name: "{{new_user}}"
    shell: /bin/bash
    groups: admin
    append: yes
     
- name: create .ssh directory if it's not exist
  file:
    path: '/home/{{new_user}}/.ssh'
    state: directory
    mode: '0755'
    
- name: create authorized_keys file and add ssh key
  copy: 
    content: "{{ssh_pubkey}}"
    dest: '/home/{{new_user}}/.ssh/authorized_keys'
    
    # - name: add ssh key to .ssh
    #   lineinfile:
    #     path: '/home/"{{new_user}}"/.ssh/authorized_keys'
    #     line: "{{ssh_pubkey}}"
    #     mode: 0600
    
- name: install nginx
  apt: 
    name: nginx
    state: latest
    update_cache: yes
    install_recommends: yes
    
- name: install postgresql
  apt: 
    pkg:
    - postgresql
    - postgresql-contrib
        
